[tool.poetry]
name = "day10"
version = "0.1.0"
description = ""
authors = ["artur"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
z3-solver = "^4.15.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
